
GET http://trabalho-finaldw-backend.onrender.com/usuarios

###

GET http://localhost:3333/usuarios?nome=joão

###

POST http://trabalho-finaldw-backend.onrender.com/usuarios
Content-type: application/json

{
  "nome": "Jose",
  "email": "jose@gmail.com",
  "telefone": "44 91234-1234",
  "endereco": "Rua das Cenouras 666",
}

###

PUT http://localhost:3333/usuarios/b8093df3-d630-429c-acb4-36b6ee74c560
Content-type: application/json
Accept-Language: pt

{
  "nome": "João da Silva",
  "email": "joaodasilva2@gmail.com",
  "telefone": "44 91234-1234",
  "endereco": "Rua das Bermudas 245",
}

###

DELETE http://trabalho-finaldw-backend.onrender.com/usuarios/473cb0fd-d705-4e2c-8f89-20a9a8239b79
